layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

sections:
  -
    title: Popular Projects
    description: My most popular open source repositories.
    sort_by: stars
    limit: 3
    exclude:
      archived: false
      forks: false
  -
    title: Recently Updated
    description: My most recently contributed projects.
    sort_by: pushed
    limit: 3
    exclude:
      archived: true
      forks: false
      # projects:
      #   - firefox-nativedark
      #   - search-deflector
      #   - vscode-smoothtype

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: spikespaz02
  # keybase: your_username
  linkedin: jacob-birkett-b4882016a
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 2512078
  telegram: spikespaz
  twitter: spikespaz
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UC8FiQJwmtUEo1vgdsQljecA

topics:
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: /images/rust-logo.svg
    description: I am actively making a point of using Rust for new projects, and refreshing the old. This is a very powerful language, and I love how it catches many (really, a lot) of my mistakes before I start debugging. This is my favorite language to work with, and I hope it gains widespread adoption in the software development industry.

  - name: D Language
    web_url: https://github.com/topics/d
    image_url: https://raw.githubusercontent.com/github/explore/7bb9edf7a8b94e13cbe6069a8f2f6a475ea7aaf2/topics/d/d.png
    description: In the last year I have fallen in love with D, a language designed as a successor to C++. While not widely known, this language is powerful and the syntax is beautiful.

  - name: Python 3
    web_url: https://github.com/topics/python3
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    description: I have about four years of experience with Python. It is my most excersised langauge, being used in the majority of my projects.

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png
    description: JavaScript is my second-best language, being used as long as Python. While not my favorite language (I consider it a necessary evil), it has proven itself useful.

donate_url: https://spikespaz.com/donate
donate_text: Donate
donate_width: 200px
