name: Rebuild GitHub Pages

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          curl \
            --fail \
            --user ${{ github.repository_owner }}:${{ github.token }} \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds
